In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

sentences = [
    "I Love WatchingTV",
    "WatchingTV is interesting",
    "NLP is fun"]

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(sentences)

print(vectorizer.get_feature_names_out())
print(X.toarray())


['fun' 'interesting' 'is' 'love' 'nlp' 'watchingtv']
[[0 0 0 1 0 1]
 [0 1 1 0 0 1]
 [1 0 1 0 1 0]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
texts = [
    "I hate this product",
    "So sad and unhappy",
    "The product is ordered",
    "The product is amazing",
    "Excellent quality and service",
    "I Love the product",
    "The item is too good",
    "Felt so bad for this product",
    "Bad product"

]

labels = [0,0,1,1,1,1,1,0,0]

vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(texts)

X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.25, random_state=42, stratify=labels)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.6666666666666666

Classification Report:
               precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       1.00      0.50      0.67         2

    accuracy                           0.67         3
   macro avg       0.75      0.75      0.67         3
weighted avg       0.83      0.67      0.67         3



In [ ]:
new_text = [" The item is bad and I did not like it"]
new_vector = vectorizer.transform(new_text)
prediction = model.predict(new_vector)

print("\nSentiment:", "Positive" if prediction[0]==1 else "Negative")



Sentiment: Negative


In [ ]:
new_text = ["So sad and unhappy"]
new_vector = vectorizer.transform(new_text)
prediction = model.predict(new_vector)

print("\nSentiment:", "Positive" if prediction[0]==1 else "Negative")


Sentiment: Negative


In [ ]:
new_text = [" I hate the product and it is so sad and unhappy"]
new_vector = vectorizer.transform(new_text)
prediction = model.predict(new_vector)

print("\nSentiment:", "Positive" if prediction[0]==1 else "Negative")


Sentiment: Positive


In [ ]:
new_text = ["I hate this product and unhappy"]
new_vector = vectorizer.transform(new_text)
prediction = model.predict(new_vector)

print("\nSentiment:", "Positive"if prediction[0]==1 else "Negative")


Sentiment: Positive


In [ ]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 39.7 MB/s eta 0:00:00


In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from gensim.models import Word2Vec
import re



In [ ]:
texts = [
    "A phone helps people talk to each other",

"We can send messages using a phone",

"A smartphone can take pictures and videos",

"You can browse the internet on your phone",

"Phones are used for studying and working",

"We can listen to music on a phone",

"A phone keeps us connected with friends and family",

"Many apps make phones more useful",

]

labels = [1,1,1,1,0,0,0,0]

In [ ]:
def preprocess(text):
  text = text.lower()
  text = re.sub(r'[^a-zA-Z]', ' ', text)
  return text.split()

corpus = [preprocess(text) for text in texts]

corpus

[['a', 'phone', 'helps', 'people', 'talk', 'to', 'each', 'other'],
 ['we', 'can', 'send', 'messages', 'using', 'a', 'phone'],
 ['a', 'smartphone', 'can', 'take', 'pictures', 'and', 'videos'],
 ['you', 'can', 'browse', 'the', 'internet', 'on', 'your', 'phone'],
 ['phones', 'are', 'used', 'for', 'studying', 'and', 'working'],
 ['we', 'can', 'listen', 'to', 'music', 'on', 'a', 'phone'],
 ['a',
  'phone',
  'keeps',
  'us',
  'connected',
  'with',
  'friends',
  'and',
  'family'],
 ['many', 'apps', 'make', 'phones', 'more', 'useful']]

In [ ]:
w2v_model = Word2Vec(
    sentences=corpus,
    vector_size=100,
    window=3,
    min_count=1,
    workers=4
    )


In [ ]:
def get_sentence_vector(sentence):
  words = preprocess(sentence)
  vectors = []
  for word in words:
    if word in w2v_model.wv:
      vectors.append(w2v_model.wv[word])
  if len(vectors) == 0:
    return np.zeros(100)

  return np.mean(vectors, axis=0)



In [ ]:
X = np.array([get_sentence_vector(text) for text in texts])
y = np.array(labels)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
    )

model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.5


In [ ]:
new_text = "A smartphone can take pictures and videos"

new_vector = get_sentence_vector(new_text)
prediction = model.predict([new_vector])

print("\nPrediction:")

if prediction[0]==1:
  print("Spam Message")
else:
  print("Not Spam")


Prediction:
Not Spam


NLP fully theory question study well